#!/usr/bin/env bash
# F1 회귀 감지 — 17 지역 백테스트 결과를 베이스라인과 비교.
# 베이스라인 0.841 (2026-04-29) 대비 Δ ≤ -0.05 시 GitHub Issue 자동 생성.
#
# 사용 (cron):
#   30 3 1 * * bash scripts/check_f1_regression.sh >> logs/f1_regression.log 2>&1
#
# 환경변수:
#   BASELINE_F1        기준 F1 (기본 0.841)
#   DELTA_THRESHOLD    회귀 임계 Δ (기본 0.05, 양수)
#   ALERT_LABELS       Issue 라벨 (기본 "regression,auto,priority:p0")
#
set -euo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

BASELINE_F1="${BASELINE_F1:-0.841}"
DELTA_THRESHOLD="${DELTA_THRESHOLD:-0.05}"
LABELS="${ALERT_LABELS:-regression,auto,priority:p0}"
ARTIFACT="analysis/outputs/backtest_17regions.json"
NOW=$(TZ=Asia/Seoul date '+%F %T KST')

if [[ ! -f "$ARTIFACT" ]]; then
    echo "[$NOW] ERROR: $ARTIFACT 없음 — backtest 실행 필요"
    exit 2
fi

# python 으로 mean_f1 추출 (jq 미설치 환경 대응)
CURRENT=$(.venv/bin/python -c "
import json, sys
try:
    d = json.load(open('$ARTIFACT'))
    print(d['summary']['mean_f1'])
except Exception as e:
    print(f'ERROR: {e}', file=sys.stderr)
    sys.exit(3)
")

# Δ = current − baseline (음수면 하락)
DELTA=$(awk "BEGIN { printf \"%.4f\", $CURRENT - $BASELINE_F1 }")

echo "[$NOW] backtest mean_f1=$CURRENT (baseline=$BASELINE_F1, Δ=$DELTA, threshold=-$DELTA_THRESHOLD)"

# Δ < -DELTA_THRESHOLD 면 회귀
is_regression=$(awk "BEGIN { print ($DELTA < -$DELTA_THRESHOLD) ? 1 : 0 }")

if (( is_regression == 0 )); then
    echo "[$NOW] ✓ F1 안정 (Δ=$DELTA ≥ -$DELTA_THRESHOLD)"
    exit 0
fi

echo "[$NOW] ⚠️ F1 회귀 감지"

if ! command -v gh >/dev/null 2>&1; then
    echo "WARN: gh CLI 미설치 — Issue 생성 스킵"
    exit 1
fi

# 동일 베이스라인·동일 월 중복 방지
month_tag=$(TZ=Asia/Seoul date +%Y-%m)
title="[regression] F1 하락 — ${month_tag} 백테스트 (Δ=$DELTA)"

if gh issue list --state open --search "$title in:title" --json title --jq '.[].title' 2>/dev/null | grep -qF "$title"; then
    echo "INFO: 중복 Issue 존재 — 스킵"
    exit 1
fi

body=$(cat <<EOF
## 자동 감지된 모델 성능 회귀

**감지 시각**: $NOW
**현재 mean F1**: $CURRENT
**베이스라인 (2026-04-29 W17 기준)**: $BASELINE_F1
**Δ (현재 − 베이스라인)**: $DELTA  (임계: -$DELTA_THRESHOLD)

## 의심 원인 (조사 우선순위)
1. **데이터 품질** — 신규 수집 주차에서 zero/null 발생? \`bash scripts/check_data_freshness.sh\`
2. **모델 드리프트** — 최근 한 달 신규 데이터로 학습 재현성 깨짐?
3. **파이프라인 변경** — \`git log --since="30 days ago" pipeline/ ml/\` 으로 회귀 후보 커밋 확인
4. **임계값/가중치 변경** — \`backend/app/config.py\` w1/w2/w3, \`scorer.py\` 임계 변경 여부

## 자료
- 산출물: \`analysis/outputs/backtest_17regions.json\`
- 학습 로그: \`logs/tft_retrain.log\` (매월 1일 02:00 KST)
- 최근 30일 git log:
  \`\`\`
  git log --oneline --since="30 days ago" pipeline/ ml/ backend/app/services/scorer.py
  \`\`\`

## 권장 조치
- [ ] 회귀 원인 식별 후 수정 PR
- [ ] 베이스라인 갱신이 정당한 경우 \`scripts/check_f1_regression.sh\` 의 \`BASELINE_F1\` 환경변수 업데이트 + 결정 로그 기록 (Notion UIS PM Hub Decisions Log)
- [ ] 해소 후 Issue close

---
🤖 Auto-generated by \`scripts/check_f1_regression.sh\` (cron: 매월 1일 03:30 KST)
EOF
)

gh issue create \
    --title "$title" \
    --body "$body" \
    --label "$LABELS" 2>&1 || echo "WARN: Issue 생성 실패"

exit 1
