#!/usr/bin/env bash
# 데이터 신선도 점검 + stale 시 GitHub Issue 자동 생성.
# check_data_freshness.sh 의 wrapper. 동일 일자 중복 issue 방지.
#
# 사용 (cron):
#   0 8 * * * bash scripts/freshness_alert.sh >> logs/freshness.log 2>&1
#
# 환경변수:
#   ALERT_LABELS   GitHub Issue 라벨 (기본 "data-quality,auto,priority:p1")
#   GH_REPO        리포 식별자 (기본: gh CLI auto-detect)
#
set -euo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

LABELS="${ALERT_LABELS:-data-quality,auto,priority:p1}"
TODAY=$(TZ=Asia/Seoul date +%F)

# JSON 모드로 점검 실행 (exit code 보존)
json_out=$(bash scripts/check_data_freshness.sh --json) && exit_code=0 || exit_code=$?

echo "[$(TZ=Asia/Seoul date '+%F %T KST')] $json_out"

# 정상이면 종료
if (( exit_code == 0 )); then
    exit 0
fi

# stale 발견 — GitHub Issue 생성 (gh CLI 필수)
if ! command -v gh >/dev/null 2>&1; then
    echo "WARN: gh CLI 미설치 — Issue 생성 스킵"
    exit "$exit_code"
fi

title="[freshness] 데이터 stale 감지 — $TODAY"

# 동일 제목의 open Issue 가 있으면 중복 생성 방지
if gh issue list --state open --search "$title in:title" --json title --jq '.[].title' 2>/dev/null | grep -qF "$title"; then
    echo "INFO: 중복 Issue 존재 — 스킵"
    exit "$exit_code"
fi

body=$(cat <<EOF
## 자동 감지된 데이터 신선도 이상

**감지 시각**: $(TZ=Asia/Seoul date '+%F %T KST')
**검사 결과 (JSON)**:
\`\`\`json
$json_out
\`\`\`

## 점검 대상
- \`ml/outputs/tft_real_metrics.json\` (TFT 학습 결과)
- \`ml/outputs/anomaly_metrics.json\` (이상탐지 모델)
- \`analysis/outputs/backtest_17regions.json\` (17 지역 백테스트)
- \`pipeline/data/kowas/kowas_*.pdf\` (KOWAS 주간 PDF)
- Backend API \`/api/v1/signals/latest\` (port 8001)

## 권장 조치
1. \`sudo systemctl status uis-scheduler\` 가동 확인
2. \`tail -100 /var/log/uis-scheduler.log\` 최근 에러 확인
3. 수동 재수집:
   \`\`\`bash
   cd $REPO_ROOT && .venv/bin/python -m pipeline.collectors.naver_backfill --weeks 1
   .venv/bin/python -m pipeline.collectors.kowas_downloader --weeks 4
   \`\`\`
4. 해소 후 \`bash scripts/check_data_freshness.sh\` exit 0 확인 → Issue close

---
🤖 Auto-generated by \`scripts/freshness_alert.sh\` (cron: 매일 08:00 KST)
EOF
)

gh issue create \
    --title "$title" \
    --body "$body" \
    --label "$LABELS" 2>&1 || echo "WARN: Issue 생성 실패"

exit "$exit_code"
